// ════════════════════════════════════════════════════
// Service Worker — PWA Maker
// Generated by PWA Maker · v1.0.0
// Cache: pwa-maker-v1.0.0
// ════════════════════════════════════════════════════

const CACHE_NAME  = 'pwa-maker-v1.0.0';
const OFFLINE_URL = 'offline.html';

// Files to pre-cache on install
const PRECACHE_URLS = [
  '/',
  'index.html',
  'offline.html',
  'manifest.json',
  'favicon.ico',
  'browserconfig.xml',
  'img/social-preview-github.png',
  'img/icon-16.png',
  'img/icon-32.png',
  'img/icon-64.png',
  'img/icon-128.png',
  'img/icon-192.png',
  'img/icon-256.png',
  'img/icon-512.png',
  'img/icon-maskable-512.png',
  'style.css',
  'script.js',
];

// ── Install ───────────────────────────────────────
self.addEventListener('install', event => {
  console.log('[SW] Install · cache:', CACHE_NAME);
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => Promise.allSettled(
        PRECACHE_URLS.map(url =>
          cache.add(url).catch(err =>
            console.warn('[SW] Could not cache:', url, err)
          )
        )
      ))
      .then(() => self.skipWaiting())
  );
});

// ── Activate ──────────────────────────────────────
self.addEventListener('activate', event => {
  console.log('[SW] Activate · removing old caches');
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CACHE_NAME).map(k => {
          console.log('[SW] Deleting cache:', k);
          return caches.delete(k);
        })
      ))
      .then(() => self.clients.claim())
  );
});

// ── Fetch ─────────────────────────────────────────
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  if (!event.request.url.startsWith(self.location.origin)) return;
  if (event.request.url.includes('browser-sync')) return;

  const url = new URL(event.request.url);

  // HTML navigation → Network first, cache fallback, offline page
  if (event.request.mode === 'navigate' || event.request.destination === 'document') {
    event.respondWith(networkFirstWithOffline(event.request));
    return;
  }

  // Images / fonts / icons → Cache first, then network
  if (isStaticAsset(event.request, url)) {
    event.respondWith(cacheFirst(event.request));
    return;
  }

  // Scripts & styles → Stale-while-revalidate
  if (isScriptOrStyle(event.request, url)) {
    event.respondWith(staleWhileRevalidate(event.request));
    return;
  }

  // Everything else → Network first
  event.respondWith(networkFirst(event.request));
});

// ── Strategies ────────────────────────────────────
async function networkFirstWithOffline(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request);
    if (cached) return cached;
    const offline = await caches.match(OFFLINE_URL);
    return offline || new Response('<h1>Offline</h1>', { headers: { 'Content-Type': 'text/html' } });
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return new Response('', { status: 408, statusText: 'Offline' });
  }
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  const networkFetch = fetch(request).then(response => {
    if (response.ok) cache.put(request, response.clone());
    return response;
  }).catch(() => cached);
  return cached || networkFetch;
}

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return await caches.match(request) ||
      new Response('', { status: 408, statusText: 'Offline' });
  }
}

// ── Helpers ───────────────────────────────────────
function isStaticAsset(req, url) {
  return req.destination === 'image' ||
    req.destination === 'font' ||
    /\.(png|jpg|jpeg|gif|webp|svg|ico|woff2?|ttf|eot)$/i.test(url.pathname);
}
function isScriptOrStyle(req, url) {
  return req.destination === 'script' ||
    req.destination === 'style' ||
    /\.(js|css)$/i.test(url.pathname);
}

// ── Background Sync ───────────────────────────────
self.addEventListener('sync', event => {
  console.log('[SW] Sync:', event.tag);
  if (event.tag === 'sync-data') {
    event.waitUntil(syncPendingData());
  }
});
async function syncPendingData() {
  // Read from IndexedDB and POST to server
  console.log('[SW] Syncing pending data...');
}

// ── Push Notifications ────────────────────────────
self.addEventListener('push', event => {
  if (!event.data) return;
  let data = {};
  try { data = event.data.json(); } catch { data = { title: event.data.text() }; }
  event.waitUntil(
    self.registration.showNotification(data.title || 'PWA Maker', {
      body:    data.body    || 'You have a new notification.',
      icon:    data.icon    || 'icon-192.png',
      badge:   data.badge   || 'icon-64.png',
      image:   data.image,
      tag:     data.tag     || 'default',
      data:    data.url     || 'https://terremoth.github.io/pwa-maker/',
      vibrate: [100, 50, 100],
      requireInteraction: false,
    })
  );
});

self.addEventListener('notificationclick', event => {
  event.notification.close();
  const url = event.notification.data || 'https://terremoth.github.io/pwa-maker/';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
      for (const c of list) {
        if (c.url === url && 'focus' in c) return c.focus();
      }
      if (clients.openWindow) return clients.openWindow(url);
    })
  );
});

// ── Messages ──────────────────────────────────────
self.addEventListener('message', event => {
  if (!event.data) return;
  if (event.data.type === 'SKIP_WAITING') self.skipWaiting();
  if (event.data.type === 'GET_VERSION' && event.ports[0]) {
    event.ports[0].postMessage({ version: CACHE_NAME });
  }
});

console.log('[SW] PWA Maker loaded · cache:', CACHE_NAME);
